---
# Playbook for web server

- name: Add epel repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Install php
  yum:
    name: php
    state: present
    name: php-mysql
    state: present

- name: Install web role dependencies
  yum:
    name: git
    state: installed

- name: Start and enable NGINX server to start at boot.
  service:
    name: nginx
    state: started
    enabled: yes

#- name: Enable the firewall ports for Nginx
#  firewalld: port=80/tcp permanent=true state=enabled immediate=yes
#  firewalld: port=443/tcp permanent=true state=enabled immediate=yes

- include: copy_code.yml
